### ISSUE TITLE
Truncated Text is not clickable

### ISSUE THREAD

**Issue by puneet-1106** [TTTAttributedLabel/TTTAttributedLabel#688]
Hi Matt,

I am using TTTAttributed label for text truncation with text "...more". But when i am trying to click it it is not clickable. Instead of this, the word before truncated text gets clicked. You can find the code below:

            let truncatedStringColour = [
                NSForegroundColorAttributeName: UIColor(red: 142.0/255.0, green: 59.0/255.0, blue: 84.0/255.0, alpha: 1.0),
                NSFontAttributeName: UIFont(name: "DINRoundOT", size: 17.0)!,
                NSLinkAttributeName : "link"]
            
            truncatedString = NSAttributedString(string: "...more", attributes: truncatedStringColour)
            
            cellIdentifier = "DescriptionDetailViewCell"
            let cell = tableView.dequeueReusableCellWithIdentifier(cellIdentifier, forIndexPath: indexPath) as! DescriptionDetailViewCell
                    
            //enabledTextCheckingTypes
            
            cell.lblDescription.enabledTextCheckingTypes = NSTextCheckingType.Link.rawValue
            
            cell.lblDescription.delegate = self
            cell.lblDescription.attributedText = attrDescription!
            
    
            
            cell.lblDescription.delegate = self
            cell.lblDescription.autoresizingMask =  UIViewAutoresizing.FlexibleWidth.union(UIViewAutoresizing.FlexibleHeight)
            
            if isNotTruncated
            {
                cell.lblDescription.numberOfLines = 0
            }
                
            else
            {

                   if let truncatStr = truncatedString
                {
                        cell.lblDescription.attributedTruncationToken = truncatStr
                    
                 }
                

                    cell.lblDescription.numberOfLines = 10
            }
            

Please try to revert me back asap as i need it badly to get solved

**Comment by puneet-1106** [comment]
It is happening when suppose in attributed text there is "\n" character.

**Comment by Linyuyu** [comment]
I have the same issue.

**Comment by buiminhhuy** [comment]
Who have solution for this?

**Comment by buiminhhuy** [comment]
Hi I have implemented to resolve this. Hope guys
//something (existed) `[truncationString appendAttributedString:attributedTruncationString];
                CTLineRef truncationLine = CTLineCreateWithAttributedString((__bridge CFAttributedStringRef)truncationString);`
`CGRect truncationLineBounds = CTLineGetImageBounds(truncationLine, c);
                CGRect truncationTokenBounds =  CTLineGetImageBounds(truncationToken, c);`
//something (existed)
`if ([attributedTruncationString attribute:NSLinkAttributeName atIndex:0 effectiveRange:&linkRange]) {
                    NSRange tokenRange = [truncationString.string rangeOfString:attributedTruncationString.string];
                    //NSRange tokenLinkRange = NSMakeRange((NSUInteger)(lastLineRange.location+lastLineRange.length)-tokenRange.length, (NSUInteger)tokenRange.length);
                    NSRange tokenLinkRange ;
                    unichar newLineChar = [[truncationString string]characterAtIndex:(lastLineRange.length - 1)];
                    unichar nextLineChar = [[truncationString string]characterAtIndex:(lastLineRange.length - 2)];
                    
                    int widthMissing = rect.size.width - (truncationLineBounds.size.width - truncationTokenBounds.size.width);
                    int numMissing = 0;
                    if (widthMissing > 0) {
                        float widthOneChar = truncationTokenBounds.size.width/tokenRange.length;
                        float floatNumMissing = widthMissing/widthOneChar;
                        numMissing = ceil(floatNumMissing);
                    }
                    
                    
                    if (([[NSCharacterSet newlineCharacterSet] characterIsMember:newLineChar] || (newLineChar == ' ' && nextLineChar == '  ') || truncationLineBounds.size.width < (rect.size.width + 10)) && (lastLineRange.length > tokenRange.length) ) {
                        tokenLinkRange = NSMakeRange((NSUInteger)(lastLineRange.location+lastLineRange.length), (NSUInteger)tokenRange.length);
                    } else if (lastLineRange.length > tokenRange.length) {
                        if (numMissing < tokenRange.length){
                            tokenLinkRange = NSMakeRange((NSUInteger)(lastLineRange.location+lastLineRange.length)-tokenRange.length+numMissing, (NSUInteger)tokenRange.length);
                        } else {
                            tokenLinkRange = NSMakeRange((NSUInteger)(lastLineRange.location+lastLineRange.length)-tokenRange.length, (NSUInteger)tokenRange.length);
                        }

                    } else {
                        int lenRemainStringEnd = (NSUInteger)attributedString.length - ((NSUInteger)(lastLineRange.location + lastLineRange.length));
                        int subLen = (NSUInteger)tokenRange.length - lenRemainStringEnd;
                        if (subLen <= 0){
                            tokenLinkRange = NSMakeRange((NSUInteger)(lastLineRange.location+lastLineRange.length), (NSUInteger)tokenRange.length);
                        } else {
                            tokenLinkRange = NSMakeRange((NSUInteger)(lastLineRange.location+lastLineRange.length), (NSUInteger)tokenRange.length - subLen);
                        }
                    }
                    
                    [self addLinkToURL:[attributedTruncationString attribute:NSLinkAttributeName atIndex:0 effectiveRange:&linkRange] withRange:tokenLinkRange];
                }
`

Any feedbacks are welcome.

**Comment by buiminhhuy** [comment]
I forked to new repository https://github.com/buiminhhuy/TTTAttributedLabel

**Comment by hammadzz** [comment]
I tried the fork by @buiminhhuy and it did not fix the issue for me.

**Comment by buiminhhuy** [comment]
You right, But I try calculation to move next or previous token. You can provide your text and truncate token. I will try to fix them.
Thanks,
Huy Bui

**Comment by stelalae** [comment]
@buiminhhuy I have the same issue. This is text

> 微信团队在2017微信公开课PRO版上发布了《2016微信数据报告》。报告中显示，微信9月平均日登录用户达到7.68亿，较去年增长35%，50%的用户每天使用微信时长达90分钟。消息日发送总次数较去年增长67%。日成功音视频通话总次数1亿次，较去年增长180%。报告还公布了各年龄层最爱听的歌曲，其中80后最爱听《走着走着就散了》，90后最爱听《演员》，而00后最爱听《真心话太冒险》。

**Comment by buiminhhuy** [comment]
Hi @stelalae, You should not set range color for "More", because this range will calculate later.
You just set truncat Color as code in swift below
```
let tailStr = NSMutableAttributedString(string: "... Read more", attributes: [
            NSForegroundColorAttributeName: Your_Color,
            NSFontAttributeName: label.font,
            NSLinkAttributeName: "READMORE:readmore:readmore"]) //detect in delegate

label.attributedTruncationToken = tailStr
```
![image](https://cloud.githubusercontent.com/assets/568664/21599542/bd6efe2a-d1a0-11e6-953b-966d82e4512a.png)

**Comment by MubeenQazi** [comment]
The clickable area is not correct. Word before "..." and read is clickable. 
Any quick fix will be appreciated.
